FROM webdevops/php-apache-dev:7.2

RUN apt-get update && apt-get install -y --no-install-recommends\
        libmagickwand-dev \
    && pecl install imagick-3.4.3 \
    && docker-php-ext-enable imagick
